[package]
name = "pyproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subprocess = "0.2.9"
libc = "0.2"
fork = "0.1.23"
pipe = "0.4.0"

[build-dependencies]
pkg-config = "0.3.29"
